# Generated by Django 5.2.2 on 2025-09-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('hypertension', models.BooleanField(default=False)),
                ('heart_disease', models.BooleanField(default=False)),
                ('smoking_history', models.CharField(max_length=20)),
                ('bmi', models.FloatField()),
                ('glucose_level', models.FloatField()),
                ('prediction', models.BooleanField()),
                ('probability_no_diabetes', models.FloatField()),
                ('probability_diabetes', models.FloatField()),
                ('confidence', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Prediction Log',
                'verbose_name_plural': 'Prediction Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
